services:
  backend:
    build: ./backend
    working_dir: /app/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  # Service for the PostgreSQL database
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

# Define a volume for storing PostgreSQL data
volumes:
  postgres_data: