version: 2
jobs:
    build:
        docker:
            - image: cimg/base:current
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: List backend ls -la
                command: docker-compose run backend ls -la
            - run:
                name: backend pwd
                command: docker-compose run backend pwd
            - run:
                name: Build Containers
                command: docker-compose build
            - run:
                name: List backend ls -la
                command: docker-compose run backend ls -la
            - run:
                name: backend pwd
                command: docker-compose run backend pwd
            - run:
                name: Run Front/Back Ends
                command: docker-compose up -d