version: 2
jobs:
    build:
        docker:
            - image: circleci/buildpack-deps:bionic-curl
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: List web ls -la
                command: docker-compose run web ls -la
            - run:
                name: web pwd
                command: docker-compose run web pwd
            - run:
                name: Build Containers
                command: docker-compose build
            - run:
                name: List web ls -la
                command: docker-compose run web ls -la
            - run:
                name: web pwd
                command: docker-compose run web pwd
            - run:
                name: Run Front/Back Ends
                command: docker compose -d up